# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogCadastrarConsulta.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogCadastrarConsulta(object):
    def setupUi(self, DialogCadastrarConsulta):
        DialogCadastrarConsulta.setObjectName("DialogCadastrarConsulta")
        DialogCadastrarConsulta.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogCadastrarConsulta.resize(853, 712)
        DialogCadastrarConsulta.setMinimumSize(QtCore.QSize(853, 712))
        DialogCadastrarConsulta.setMaximumSize(QtCore.QSize(853, 712))
        DialogCadastrarConsulta.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label = QtWidgets.QLabel(DialogCadastrarConsulta)
        self.label.setGeometry(QtCore.QRect(0, 10, 851, 81))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogCadastrarConsulta)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 71, 31))
        self.label_2.setObjectName("label_2")
        self.txt_cpf = QtWidgets.QLineEdit(DialogCadastrarConsulta)
        self.txt_cpf.setInputMask("000.000.000-00")
        self.txt_cpf.setGeometry(QtCore.QRect(70, 130, 201, 27))
        self.txt_cpf.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txt_cpf.setObjectName("txt_cpf")
        self.btn_buscar_cpf = QtWidgets.QPushButton(DialogCadastrarConsulta)
        self.btn_buscar_cpf.setGeometry(QtCore.QRect(280, 130, 75, 27))
        self.btn_buscar_cpf.setObjectName("btn_buscar_cpf")
        self.txt_nome = QtWidgets.QLineEdit(DialogCadastrarConsulta)
        self.txt_nome.setEnabled(False)
        self.txt_nome.setGeometry(QtCore.QRect(70, 200, 491, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_nome.setFont(font)
        self.txt_nome.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_nome.setInputMask("")
        self.txt_nome.setPlaceholderText("")
        self.txt_nome.setObjectName("txt_nome")
        self.label_3 = QtWidgets.QLabel(DialogCadastrarConsulta)
        self.label_3.setGeometry(QtCore.QRect(70, 170, 71, 31))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(DialogCadastrarConsulta)
        self.label_6.setGeometry(QtCore.QRect(70, 230, 161, 31))
        self.label_6.setObjectName("label_6")
        self.txt_plano_saude = QtWidgets.QLineEdit(DialogCadastrarConsulta)
        self.txt_plano_saude.setEnabled(False)
        self.txt_plano_saude.setGeometry(QtCore.QRect(70, 260, 491, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_plano_saude.setFont(font)
        self.txt_plano_saude.setPlaceholderText("")
        self.txt_plano_saude.setObjectName("txt_plano_saude")
        self.label_7 = QtWidgets.QLabel(DialogCadastrarConsulta)
        self.label_7.setGeometry(QtCore.QRect(70, 290, 101, 31))
        self.label_7.setObjectName("label_7")
        self.txt_numero_plano = QtWidgets.QLineEdit(DialogCadastrarConsulta)
        self.txt_numero_plano.setEnabled(False)
        self.txt_numero_plano.setGeometry(QtCore.QRect(70, 320, 201, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_numero_plano.setFont(font)
        self.txt_numero_plano.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.txt_numero_plano.setPlaceholderText("")
        self.txt_numero_plano.setObjectName("txt_numero_plano")
        self.label_8 = QtWidgets.QLabel(DialogCadastrarConsulta)
        self.label_8.setGeometry(QtCore.QRect(70, 360, 161, 31))
        self.label_8.setObjectName("label_8")
        self.txt_Dentista = QtWidgets.QLineEdit(DialogCadastrarConsulta)
        self.txt_Dentista.setGeometry(QtCore.QRect(70, 620, 331, 27))
        self.txt_Dentista.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_Dentista.setInputMask("")
        self.txt_Dentista.setObjectName("txt_Dentista")
        self.label_4 = QtWidgets.QLabel(DialogCadastrarConsulta)
        self.label_4.setGeometry(QtCore.QRect(70, 590, 181, 31))
        self.label_4.setObjectName("label_4")
        self.btn_buscar_dentista = QtWidgets.QPushButton(DialogCadastrarConsulta)
        self.btn_buscar_dentista.setGeometry(QtCore.QRect(410, 620, 75, 27))
        self.btn_buscar_dentista.setObjectName("btn_buscar_dentista")
        self.btn_cadastrar = QtWidgets.QPushButton(DialogCadastrarConsulta)
        self.btn_cadastrar.setGeometry(QtCore.QRect(548, 650, 111, 41))
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.btn_cancelar = QtWidgets.QPushButton(DialogCadastrarConsulta)
        self.btn_cancelar.setGeometry(QtCore.QRect(670, 650, 111, 41))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.calendarConsulta = QtWidgets.QCalendarWidget(DialogCadastrarConsulta)
        self.calendarConsulta.setGeometry(QtCore.QRect(70, 390, 461, 181))
        self.calendarConsulta.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.SingleLetterDayNames)
        self.calendarConsulta.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarConsulta.setNavigationBarVisible(True)
        self.calendarConsulta.setDateEditEnabled(True)
        self.calendarConsulta.setObjectName("calendarConsulta")

        self.retranslateUi(DialogCadastrarConsulta)
        QtCore.QMetaObject.connectSlotsByName(DialogCadastrarConsulta)

    def retranslateUi(self, DialogCadastrarConsulta):
        _translate = QtCore.QCoreApplication.translate
        DialogCadastrarConsulta.setWindowTitle(_translate("DialogCadastrarConsulta", "Cadastrar Consulta"))
        self.label.setText(_translate("DialogCadastrarConsulta", "<html><head/><body><p><span style=\" font-size:48pt;\">Cadastrar Consulta</span></p></body></html>"))
        self.label_2.setText(_translate("DialogCadastrarConsulta", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">CPF:</span></p></body></html>"))
        self.btn_buscar_cpf.setText(_translate("DialogCadastrarConsulta", "Buscar"))
        self.label_3.setText(_translate("DialogCadastrarConsulta", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Nome:</span></p></body></html>"))
        self.label_6.setText(_translate("DialogCadastrarConsulta", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Plano de Saúde:</span></p></body></html>"))
        self.label_7.setText(_translate("DialogCadastrarConsulta", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Nº Plano:</span></p></body></html>"))
        self.label_8.setText(_translate("DialogCadastrarConsulta", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Data Consulta:</span></p></body></html>"))
        self.txt_Dentista.setPlaceholderText(_translate("DialogCadastrarConsulta", "Digite o nome"))
        self.label_4.setText(_translate("DialogCadastrarConsulta", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Buscar Dentista:</span></p></body></html>"))
        self.btn_buscar_dentista.setText(_translate("DialogCadastrarConsulta", "Buscar"))
        self.btn_cadastrar.setText(_translate("DialogCadastrarConsulta", "Cadastrar"))
        self.btn_cancelar.setText(_translate("DialogCadastrarConsulta", "Cancelar"))

